### ISSUE TITLE
typo in class 8 prep

### ISSUE THREAD

**Issue by seraries** [LaunchCodeEducation/web-fundamentals#8]
http://education.launchcode.org/web-fundamentals/class-prep/8/. End of first paragraph says "by adding _and_ element to a list" but should be "an" . Also typo with 2nd paragraph: " the most common way store data." should be "to store data". And after intro to lambda: "If you get stuck on this quick, don't worry about it too much." needs a noun after "quick", "fix" maybe?

**Comment by morrme** [comment]
@seraries Maybe just "If you get stuck on this. don't worry about it too much." without the quick?
